### ISSUE TITLE
gogotester_python里哪个文件才是google的ip池？

### ISSUE THREAD

**Issue by sbw983** [NKUCodingCat/gogotester_python#10]
RT

看见有三个文件 gcc.txt,gcc_test.txt和Ip_in.txt，哪一个才是？
谢谢

**Comment by sbw983** [comment]
http://ipinfo.io/AS15169
这里列出了google美国的ip池，能在其他地方找到google ip池吗？

**Comment by NKUCodingCat** [comment]
=。=啊这个问题啊……我是把挂在google下的IP都贴进去了……具体是哪个我也不记得了一般就用多的那个就好……

**Comment by NKUCodingCat** [comment]
https://github.com/NKUCodingCat/gogotester_python/blob/master/src/Main_Gevent.py#L43
一般用的是ggc.txt， 可以自己看着改，用的网站和你一样……至于美国什么的我还真没注意过

**Comment by NKUCodingCat** [comment]
http://bgp.he.net/search?search%5Bsearch%5D=google&commit=Search
这个网站舒服一点

**Comment by sbw983** [comment]
11月开始搜出来的v4地址基本都不能用，即使能用也极不稳定。只能用V6的地址了。好像google美国的v4地址都被封了，
所以想找google其他数据中心的地址.

**Comment by NKUCodingCat** [comment]
你看我最后给的网站里面不止usa的旗子对吧……
PS: 我这段时间在墙外，并不知道发生了什么
