### ISSUE TITLE
Timeout 可以用小数点吗

### ISSUE THREAD

**Issue by seozed** [NKUCodingCat/gogotester_python#2]
比如0.5秒内的

**Comment by NKUCodingCat** [comment]
啊哈好像是可以的……
乃看看代码如果我没有强行int()一下的话那就没什么问题

嗯

**Comment by NKUCodingCat** [comment]
啊好吧我扫了一眼，并没有，所以都是可以用小数的说

**Comment by seozed** [comment]
非常感谢

328134421@qq.com

发件人： JingTao Chen
发送时间： 2015-06-17 15:51
收件人： NKUCodingCat/gogotester_python
抄送： qsnow6
主题： Re: [gogotester_python] Timeout 可以用小数点吗 (#2)
啊好吧我扫了一眼，并没有，所以都是可以用小数的说
