### ISSUE TITLE
可否设定一下ip数量

### ISSUE THREAD

**Issue by PvCDp** [NKUCodingCat/gogotester_python#6]
一直扫描不知道什么是否结束，有什么好办法，可否设定一下ip数量，够了就自动停止？

**Comment by NKUCodingCat** [comment]
相关设置位于config.ini， 可以分别设置ipv4和ipv6的限制以及线程数等

**Comment by PvCDp** [comment]
多谢。扫描效率比较低，一个多小时只找到了6个。

**Comment by NKUCodingCat** [comment]
效率取决于所处的网络环境……这个基本没办法
不如试试把延时加高点？
