### ISSUE TITLE
Windows下 Mcafee报告有病毒

### ISSUE THREAD

**Issue by sbw983** [NKUCodingCat/gogotester_python#7]
2016/1/21   8:18:47 已删除   **\*  \gogotester_python-master\packed\gogotester_python.exe Artemis!40C21A6F43F9 (特洛伊)

**Comment by NKUCodingCat** [comment]
o(_￣▽￣_)ブ等我回去再改

**Comment by NKUCodingCat** [comment]
氖再下一次试试……？

**Comment by sbw983** [comment]
等每天上班再试一下了，我家里用的Linux

**Comment by sbw983** [comment]
没问题了

**Comment by NKUCodingCat** [comment]
OK
