### ISSUE TITLE
为何运行了1.5天还不停止

### ISSUE THREAD

**Issue by fhzyfjy** [NKUCodingCat/gogotester_python#8]
WIN7系统 下载该软件按说明启动运行，已经1.5天，仍在扫IP，没有停止。不知何原因。谢谢

**Comment by NKUCodingCat** [comment]
能否给个截图，或者复制一下最近的log上来呢

**Comment by fhzyfjy** [comment]
这是packed下面的log。谢谢。祝春节快乐、身体健康
{"Status": "GA", "ip": "173.194.2.22", "cname": "_.c.docs.google.com"}
{"Status": "GA", "ip": "173.194.48.174", "cname": "_.c.docs.google.com"}
{"Status": "GA", "ip": "189.247.135.70", "cname": "_.googlevideo.com"}
{"Status": "GA", "ip": "192.232.16.78", "cname": "_.googlevideo.com"}
{"Status": "GA", "ip": "173.194.132.215", "cname": "_.c.docs.google.com"}
{"Status": "GA", "ip": "208.117.227.104", "cname": "_.googlevideo.com"}
{"Status": "GA", "ip": "104.237.190.89", "cname": "_.googlevideo.com"}
{"Status": "GA", "ip": "216.68.10.135", "cname": "_.googlevideo.com"}
{"Status": "GA", "ip": "74.125.155.21", "cname": "_.c.docs.google.com"}
{"Status": "GA", "ip": "173.194.158.151", "cname": "_.c.docs.google.com"}
{"Status": "GA", "ip": "216.68.10.158", "cname": "*.googlevideo.com"}

2016-02-11 17:59 GMT+08:00 JingTao Chen notifications@github.com:

**Comment by NKUCodingCat** [comment]
因为默认扫到40个ipv4的ggc可用ip才会停止，所以如果你的网络环境不好的话会运行很久……以及ipv6的可用性判断不一定好用，所以如果运行时间长的话可以在config.ini里面把ipv6那里设为0这样就能禁用ipv6扫描了……以及我的意思是把命令行窗口里面的东西截个图啦……

**Comment by fhzyfjy** [comment]
1、截图见下
[image: 内嵌图片 1]
2、是把packed中config.ini的v6=80改为v6=0?
3、scr中的config.ini的v6是否更改为0？

 谢谢

在 2016年2月12日 下午8:46，JingTao Chen notifications@github.com写道：

**Comment by NKUCodingCat** [comment]
1, 改packed里的config.ini的就行
2. 图被吃了，原因不明
3. 最近邮箱抽风，不能及时回复，请谅解

**Comment by fhzyfjy** [comment]
非常感谢。我下载了你的最新版0.92（启动后还是显示0.9）.但一个IP都扫不出来了。

2016-02-13 10:21 GMT+08:00 JingTao Chen notifications@github.com:

**Comment by NKUCodingCat** [comment]
一般来说……这都是因为你所在的地方的外网带宽不行……找个国内服务器转发吧

**Comment by fhzyfjy** [comment]
我这宽带速度达7.6M/s。今天扫了一下午，一个也没有扫出。不过还是谢谢你的无私奉献和耐心讲解。祝情人节愉快。

2016-02-13 11:35 GMT+08:00 JingTao Chen notifications@github.com:

**Comment by NKUCodingCat** [comment]
外网是指国外的网站……访问国内快并没有什么用……
建议调高超时时长，以上

**Comment by fhzyfjy** [comment]
国外的网站是在IE中设置代理吧？谢谢

2016-02-14 19:04 GMT+08:00 JingTao Chen notifications@github.com:

**Comment by NKUCodingCat** [comment]
虽然不知道你想表达什么但是总感觉哪里不对……

**Comment by fhzyfjy** [comment]
我是说把IE浏览器设置为代理上外网后再打开你的软件扫IP。谢谢

2016-02-14 23:37 GMT+08:00 JingTao Chen notifications@github.com:

**Comment by NKUCodingCat** [comment]
并不是follow IE的代理设置呢……这玩意测试的是能直连的google IP的←_←……
