### ISSUE TITLE
无法检测IPV6了

### ISSUE THREAD

**Issue by Nelocope** [NKUCodingCat/gogotester_python#9]
更新了最新版，但是无法检测IPV6，显示 “ipV6 is not available”

查看Readme文件说是未开启，所以是修改“limit_v6=0”的数字“0”为其他来开启么？

还有就是检测IPV6的网站，实际我已经接入了IPV6，用其他网站测试能检测到，但是您所给的那个检测不出我的地址，我在想是不是这个也是对 “ipV6 is not available”这个结果有影响？

**Comment by NKUCodingCat** [comment]
啊哈把那个0改成大于0的任意整数就好……那个数是搜索到的ipv6的ip数量上限
那个检测的网站仅供参考，请自行决定是否开启
感谢您的使用，来自快要开学心很累的喵

**Comment by Nelocope** [comment]
啊呀 感谢回复~~~

我改动了数字 但是还是显示 "IPV6 is not available"

上午用上一个版本检测发现速度很慢，相比于年前哈，然后改换新版本就悲剧了~

开启的意思就是改动0为任意大于0的整数是嘛

同开学，不开心~~~

**Comment by NKUCodingCat** [comment]
嘛……氖可以暂时用着上一个版本……这个版本估计还是bug多……

**Comment by Nelocope** [comment]
好嘞 辛苦~~~

**Comment by NKUCodingCat** [comment]
嘛……氖现在可以试试下一下最新版来看是否有ipv6啦~~修了半天我觉得应该没啥问题了吧

**Comment by Nelocope** [comment]
搞定！！！
跪服程序帝哇~~~

**Comment by Nelocope** [comment]
顺便 再拜一下python~~~
哈哈~~~
